azure/resource-quotas.sh

This PR enhances `resource-quota.sh` to:
- add check to input location to restraint it in the available location list
- add check to input PG types to restraint it in the available pg types list  
- hint in the usage message for available locations and pg types
- minor usage message bug fix

Add available regions and PG types checks and hint for resource-quota.sh

---

README.md
api/get-token.sh

This PR adds a new script named `get-token.sh` to:
- follow the standard OAuth0 Device Code flow to get a series of token used for accessing EDB Cloud API
- refresh the tokens by using the standard *refreshing* flow
```sh
get-token.sh
Get Tokens for EDB Cloud API
Usage:
./get-token.sh [flags] [options]
--format  json | plain         output format
--refresh <refresh_token>      [optional] query for tokens again by the given refresh_token
this revokes and rotates the given refresh token,
please remember the newly returned refresh_token for
the next use
Reference: https://www.enterprisedb.com/docs/edbcloud/latest/reference/
```
```
./get-token.sh -o plain
Please login to https://edbcloud.us.auth0.com/activate?user_code=ZMNX-VVJT with your EDB Cloud account
Have you finished the login …
```

Add a new script for getting token to access EDB Cloud API

---

api/get-token.sh
azure/create-spn.sh
azure/resource-quotas.sh

This PR:
- Update `get-token.sh` script with latest token exchange flow on EDB Cloud authentication system
- Disable to output the `id_token` in `get-token.sh` as EDB Cloud does not use it at the moment.
- Update all the scripts with a rich comments inside for the reader to understand what this script is about.

Update get-token.sh script with latest token exchange flow on EDB Cloud authentication system

---

azure/azure-preflight.sh

Add Standard_D2_v4 to the preflight check
Because futur merged default node pool will use Standard_D2_v4 sku
```
./azure-preflight.sh --location eastus --pgtype e16s_v3 --endpoint public
#######################
#######################
EnvironmentName    HomeTenantId                          IsDefault    Name         State    TenantId
-----------------  ------------------------------------  -----------  -----------  -------  ------------------------------------
AzureCloud         fb0c7e10-e8dc-41ff-8203-2faa9e0b3d0f  True         development  Enabled  fb0c7e10-e8dc-41ff-8203-2faa9e0b3d0f
#######################
#######################
Namespace                                RegistrationPolicy    RegistrationState    ProviderAuthorizationConsentState
--------------------------------------- …
```

feat(UPM-3181): Add Standard_D2_v4 preflight check

---

azure/biganimal-preflight-azure

We need to use the pg_instance_type from the input argument to check the availability of SKU VM from Azure. Instead of just assuming that the end user is always using E2s_v3.

use input pgtype for sku vm type check

---

azure/biganimal-preflight-azure

This PR:
- drops the support of Bash v3 and below (the Azure command console uses v5 now)
- support for wider instance-types on Azure which have all been tested

azure-preflight-check: support rich instance types

---

README.md
api/get-token.sh

the free trial user now owns one new dedicated client application to use to finish the OAuth2 device-flow authentication.
This PR is to support that. 
The old client ID is still available at this moment.

update get-token.sh to support new free trial user login experience

---

azure/biganimal-csp-preflight
azure/biganimal-csp-setup
azure/biganimal-preflight-azure

https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration#install-a-previous-version 
We will need further change to the script to support 2.37.0

restrict azure-cli < 2.37.0 for Microsoft Azure Graph API changes.

---

aws/biganimal-csp-preflight
azure/biganimal-csp-preflight

This PR adds regions Azure centralindia and AWS Mumbai (ap-south-1)

adding regions Azure centralindia and AWS Mumbai (ap-south-1)

---

README.md
azure/biganimal-csp-setup

The `wget` is by default not installed on mac system. This PR is to mention the `wget` is needed as well like `jq` for `azure-csp-setup` script.

Update README.md and azure-csp-setup script to tell wget is needed

---

aws/biganimal-csp-setup

`aws iam get-role` error message is useless since we only use the return code to see if needs to create a service-linked role.

fix(UPM-14574): redirect useless error

---

utils/superset/README.md
utils/superset/db_name_change.py

Add shebang in the python script.
The current python script to change the database name needs an explicit call to `python3`. With the shebang line and making the script executable, we'd be getting rid of `python3 script name and simply executing the script `./script-name`
Add a shebang line in the script and relevant changes in the README.
Tested locally.
_Provide a bulleted list of GitHub issues, or any other references (mailing list discussion, etc...) that reviewers can reference
for additional information regarding scope of the pull request._

chore(UPM-12468): Add shebang to the database name change script

---

azure/biganimal-csp-setup

Tested with
```
$ azure/biganimal-csp-setup -d valerio-test-spn-new -s <SUBSCRIPTION_ID>
...
Creating Azure AD Service Principal in subscription <SUBSCRIPTION_ID>...
Updating Azure AD Service Principal application <SPN_ID> and configuring its access to Azure resources in subscription <SUBSCRIPTION_ID>...
Waiting 15 seconds for Azure AD Service Principal to propagate...
...
```
and with
```
$ azure/biganimal-csp-setup -d valerio-test-spn-new -s <SUBSCRIPTION_ID> -i <SPN_ID> -t <TENANT_ID>
...
Checking if Azure AD Service Principal application <SPN_ID> already exists in subscription <SUBSCRIPTION_ID> and tenant <TENANT_ID>...
Updating Azure AD Service Principal application <SPN_ID> in subscription <SUBSCRIPTION_ID> and tenant <TENANT_ID>...
Waiting 15 seconds for Azure AD Service Principal …
```

fix: azure setup csp now retries SPN role assignment until it succeed

---

gcp/biganimal-csp-preflight

Tested with
```
➜  cloud-utilities git:(upm-21297) ✗ gcp/biganimal-csp-preflight -i e2-standard-8 -x single -e public -r --onboard <PROJECT-ID> us-east1
Run GCP Preflight Checks with gcloud cli 436.0.0
####################################
####################################
NAME                                     RESULT
---------------------------------------  ---------
autoscaling.googleapis.com               Enabled
cloudapis.googleapis.com                 Enabled
compute.googleapis.com                   Enabled
container.googleapis.com                 Enabled
iam.googleapis.com                       Enabled
iamcredentials.googleapis.com            Enabled
run.googleapis.com                       Enabled
secretmanager.googleapis.com             Enabled
storage.googleapis.com …
```

fix: refine GCP CPU quota check

---

gcp/biganimal-csp-setup

when the GCP SA is having less than 2 keys:
```
gcp/biganimal-csp-setup -p <GCP_PROJECT_ID> -s "sa-test" -r "role_test"
Run GCP CSP setup with gcloud cli 439.0.0
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 17242  100 17242    0     0  57628      0 --:--:-- --:--:-- --:--:-- 58646
Downloaded /Users/valeriodelsarto/Git/cloud-utilities/biganimal_GCP_baserole.yaml
Updating GCP custom role biganimal_role_test within GCP project <GCP_PROJECT_ID>...
GCP service account biganimal-sa-test already exists within GCP project <GCP_PROJECT_ID>...
Allowing GCP service account biganimal-sa-test to use the GCP project <GCP_PROJECT_ID>...
Updated IAM policy for project [<GCP_PROJECT_ID>].
Creating a GCP service account …
```

fix: GCP setup can handle multiple keys in the same SA

---

gcp/biganimal-csp-preflight

`E2_CPUS` & `N1_CPUS` in fact are shared `CPUS`
https://cloud.google.com/compute/resource-usage
```
$ ./biganimal-csp-preflight -i e2-highcpu-4 -x ha -e private -r development-data-bah us-east1
Resource              Quota Name                            Limit    Used     Required    Gap      Suggestion 
--------              ----------                            ----     -----    --------    ---      ---------- 
n2-standard-2 vCPUs   N2_CPUS                               500      12       6           482      OK
Shared-Core vCPUs     CPUS                                  2400     2        14          2384     OK
Static IP Addresses   STATIC_ADDRESSES                      700      1        1           698      OK
VPCs                  NETWORKS                              50       18 …
```

fix(UPM-22519): validate quota errors

---

gcp/biganimal-csp-preflight

The preflight script should be updated to now account for 4 VMs of default node

fix(UPM-22037): update the pre-flight script

---

aws/biganimal-csp-preflight

```bash
$ bash aws/biganimal-csp-preflight -i r5.16xlarge -x eha -e public -r --onboard <AWS_ACCOUNT_ID> us-east-1
Run AWS Preflight Checks with aws-cli 2.13.3
##############################################
Checking Service Quotas Limits on us-east-1...
##############################################
Resource              Quota Name                            Limit    Used     Required    Gap      Suggestion
--------              ----------                            ----     -----    --------    ---      ----------
m5(a).large vCPUs     Running On-Demand Standard instances  716      0        6           514      OK
r5.16xlarge vCPUs     Running On-Demand Standard instances  716      0        192         514      OK
c5.large vCPUs        Running On-Demand Standard instances  716      0 …
```

fix: Adding 'SG rules per SG' quota suggestion for EHA on AWS

---

azure/biganimal-csp-preflight

```
$ user_name="USER#EXT#@DOMAIN.com"
$ az role assignment list --assignee "${user_name//\#/%23}" --include-groups --include-inherited --role Owner -o json --only-show-errors | jq length
ERROR: Cannot find user or service principal in graph database for 'USER%23EXT%23@DOMAIN.com'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id USER%23EXT%23@DOMAIN.com'.
$ az role assignment list --assignee "${user_name//\#/%23}" --include-groups --include-inherited --role Owner -o json --only-show-errors 2> /dev/null || echo "{}" | jq length
0
```

fix: not display unneeded errors on role assignment validations on Azure preflight

---

gcp/biganimal_GCP_baserole.yaml

updating permissions for gcp so that it can run without error with the new updates to flux 
re: https://github.com/fluxcd/flux2/pull/3879

feat(UPM-24309): updates for contain resource quotas

---

azure/azure-policies-dump

Customer’s Azure subscriptions often have some in-house policies set up, Some enforcement policies may have conflicts with BigAnimal infrastructure setting, and block the BigAnimal deployment. To detect the potential conflicts before the deployment. We can create a shell utility, ask the customer to run it from the azure cloud shell, dump all their organizational policy, and then send it back to us to do analysis. 
We can publish this utility from EnterpriseDB/cloud-utilities repo, it allows customers to download it directly.
```bash
➜ ./azure-policies-dump --subscription 22180ed3-30ee-4fc7-8e74-82d5b80f3d0b
Change your Azure CLI context to the subscription: 22180ed3-30ee-4fc7-8e74-82d5b80f3d0b
Dump all the effective policy assignments for the current context subscription...
Dump all …
```

feat(UPM-30903): add the azure policies dumper script

---

azure/biganimal-csp-setup

The prolog contains out-of-date information saying that we are "granting the owner role of subscription" to the connection spn. Which is misleading and concerns customers.

fix(UPM-34333): correct the out-of-date prolog of the script
