README.md
azure/create-spn.sh

Implement a script to create root SPN with Owner role in provided Azure subscription. The output can be used in EDB Cloud signup page.

feat(UPM-2185): Implement a script to create root SPN

---

azure/create-spn.sh

fix(UPM-2185): correct the help info

---

azure/create-spn.sh

Force to use json format since sometimes user configured the format as table.

fix(UPM-2185): force to use json format

---

azure/resource-quotas.sh

add listing skus
```sh
$ ./azure/resource-quotas.sh --location australiaeast --pgtype e64s_v3 --endpoint public  --ha --with-infra
EnvironmentName    HomeTenantId                          IsDefault    Name         State    TenantId
-----------------  ------------------------------------  -----------  -----------  -------  ------------------------------------
AzureCloud         fb0c7e10-e8dc-41ff-8203-2faa9e0b3d0f  True         development  Enabled  fb0c7e10-e8dc-41ff-8203-2faa9e0b3d0f
Resource                         Limit    Used     Available   Gap      Suggestion 
--------                         -----    ----     ---------   ---      ---------- 
Total Regional vCPUs             270      44       226         22       OK
Standard DSv2 Family vCPUs       40       24       16          10 …
```

Add listing SKUs

---

README.md
azure/resource-quotas.sh

This PR:
- enhance the `resource-quotas.sh` to check the unregistered Azure provider namespace that EDB Cloud requires to use
- colorful-lize the checking result for different type of check
- summarize the overall check result and output it at last.
Now the script of `resource-quotas.sh` can give
```sh
./resource-quotas.sh  -l westus2 --pgtype e64s_v3 --endpoint public --ha --with-infra
#######################
#######################
EnvironmentName    HomeTenantId                          IsDefault    Name        State    TenantId
-----------------  ------------------------------------  -----------  ----------  -------  ------------------------------------
AzureCloud         fb0c7e10-e8dc-41ff-8203-xxxxxxxxxxxx  True         production  Enabled  fb0c7e10-e8dc-41ff-8203-xxxxxxxxxxxx …
```

update resource-quotas.sh script to check providers

---

README.md
api/get-token.sh
azure/azure-preflight.sh
azure/create-spn.sh

This PR updates the entire repo with the new branding. EDB Cloud has been deprecated and BigAnimal has been introduced throughout, including plain text, variable names, urls, and more.

fix(UPM-3017): Rebrands the repo with appropriate changes

---

azure/azure-preflight.sh

Add Azure subscription state check and echo tenant ID.

fix(UPM-2952): add Azure subscription check

---

azure/azure-preflight.sh

Check if the user has owner role in the current subscription.

Add the current user role check

---

azure/azure-preflight.sh

Need to check additional provider of "Microsoft.ContainerInstance".

add provider check against ContainerInstance

---

azure/azure-preflight.sh

1. Check if the user type is Member.
2. Add an example for opening Azure ticket.

Check user type and add open Azure ticket example

---

azure/azure-preflight.sh

1. Modify the role checking message based on the support engineer comment.
2. Remove the `az support` command because it will need additional installation.

Enhance the script based on support eng comments

---

azure/azure-preflight.sh

Update preflight checks for "Standard ESv3 Family vCPUs" with "--with-infra" parameter

Update preflight checks for Standard ESv3 Family vCPUs

---

azure/azure-preflight.sh

- Update regional vCPUs check
- Add "Microsoft.AlertsManagement" in required provider list

Update regional vCPUs check

---

azure/azure-preflight.sh

update available azure regions : added 4 regions
australiaeast, norwayeast, southeastasia, westus3
added:
- REQUIRED_PROVIDER: "Microsoft.Capacity" - needed for checking and updating quotas via Azure API Management
Added additional Azure regions that BigAnimal now supports.

Update available azure regions : Added 7 regions

---

azure/azure-preflight.sh
azure/create-spn.sh

Features:
- Create SPN with MS Graph API permissions:
- Create SPN with subscription owner
- Assign SPN and Signed user as App and SPN owner
- Grant admin consent
BUG FIXES:
- Update validate user check

preflight check enhancement

---

azure/biganimal-preflight-azure

This PR updates the `biganimal-preflight-azure` script with better help message and comment to explain what it does need.

update help message and use region instead of location

---

azure/create-spn.sh

- Update script return code
- Update script function name
- Add more comments

Fix script return code issue

---

azure/biganimal-preflight-azure

fix:  biganimal-preflight-azure - corrected ESv3 quota gap output

fix: biganimal-preflight-azure - corrected gap_esv3_vcpu

---

azure/biganimal-preflight-azure

azure/biganimal-preflight-azure: increase infra_vcpus 8 > 14

biganimal-preflight-azure: bump required infra_vcpus

---

aws/biganimal-csp-setup

Reverts EnterpriseDB/cloud-utilities#60

Revert "fix(UPM-7331): added policy arn to ba-passport.json."

---

azure/biganimal-csp-setup

Additional info here https://github.com/Azure/azure-cli/issues/22580

fix: azure/biganimal-csp-setup supports for Azure CLI 2.37 and greater

---

azure/biganimal-csp-setup
azure/biganimal-poweruser-template.json

Reduce Azure permission set to
```
"permissions": [
{
"actions": [
"Microsoft.AlertsManagement/*",
"Microsoft.Authorization/*",
"Microsoft.Capacity/*",
"Microsoft.Compute/*",
"Microsoft.ContainerInstance/*",
"Microsoft.ContainerService/*",
"Microsoft.Insights/*",
"Microsoft.KeyVault/*",
"Microsoft.ManagedIdentity/*",
"Microsoft.Network/*",
"Microsoft.OperationalInsights/*",
"Microsoft.OperationsManagement/*",
"Microsoft.Portal/*",
"Microsoft.Resources/*",
"Microsoft.Storage/*",
"Microsoft.network/*"
],
```

feat(UPM-9901): update the csp-setup script to create the custom role

---

azure/biganimal-csp-setup

Make setup-csp auto download its dependency from the public repo.

UPM-9901: Auto download the dependent template file

---

azure/biganimal-csp-setup

Fix the file path as it errors out after downloading the link.

fix(UPM-9901): fix the file path

---

utils/superset/README.md

Update README with the EDB Postgres Distributed instead of PGD.

docs(UPM-10326): Update README for superset dashboard

---

gcp/biganimal-csp-preflight

Sample run:
```
$ gcp/biganimal-csp-preflight -i e2-standard-8 -x single -e public -r --onboard <PROJECT-ID> us-east1
Run GCP Preflight Checks with gcloud cli 434.0.0
####################################
####################################
NAME                                     RESULT
---------------------------------------  ---------
autoscaling.googleapis.com               Enabled
cloudapis.googleapis.com                 Enabled
compute.googleapis.com                   Enabled
container.googleapis.com                 Enabled
iam.googleapis.com                       Enabled
iamcredentials.googleapis.com            Enabled
run.googleapis.com                       Enabled
secretmanager.googleapis.com             Enabled
storage.googleapis.com                   Enabled …
```

feat: adding first version of GCP preflight check
